# Generated by Django 5.2.4 on 2025-07-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='period_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
