# Generated by Django 5.2.4 on 2025-07-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='content_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='summary_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
